force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>C-{00}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Predefined Checklist Items are auto-generated if a Checklist Template is selected.</inlineHelpText>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipLabel>Checklists</relationshipLabel>
    <relationshipName>Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Checklist Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CheckListTriggerHelper.cls
/*
     * @description: Helper class for CheckListTriggerHandler class. Used to run the Aggregate query under "Without Sharing" class
     * to get how many Checklists are created using particular Checklist Templates irrespective of the access permission and return it, 
     * later it will be updated in CheckListTriggerHandler class in the Template Used Count field.
     * @Author: Kandisa Technologies
*/

public without sharing class CheckListTriggerHelper {
    /*
     * @description: To fetch Count of all the Checklists which are created using Checklist Templates irrespective of ownership
     * @return: List<AggregateResult>
     * @param: templateIds
    */ 
    public static List<AggregateResult> getChecklistTemplateAggregate(Set<Id> templateIds){
        return new List<AggregateResult>([SELECT Checklist_Template__c, COUNT(Id) recCount
                                                      FROM Checklist__c WHERE Checklist_Template__c IN: templateIds
                                                      WITH SYSTEM_MODE 
                                                      GROUP BY Checklist_Template__c ]);
    }
}