force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>C-{00}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/Checklist_Item_Count__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Item_Count__c</fullName>
    <label>Checklist Item Count</label>
    <summaryForeignKey>Checklist_Item__c.Checklist__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Predefined Checklist Items are auto-generated if a Checklist Template is selected.</inlineHelpText>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipLabel>Checklists</relationshipLabel>
    <relationshipName>Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Checklist_Title__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Title__c</fullName>
    <label>Checklist Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Due_Days__c.field-meta.xml
<CustomField>
    <fullName>Due_Days__c</fullName>
    <inlineHelpText>Number of days the checklist is due from the date of creation.</inlineHelpText>
    <label>Due Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Percentage_Completion__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Completion__c</fullName>
    <formula>FLOOR(( Checklist_Item_Checked_Count__c  /  Checklist_Item_Count__c ) * 100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percentage Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Sequential__c.field-meta.xml
<CustomField>
    <fullName>Sequential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sequential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Checklist Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Template__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>When it&apos;s Active, the Template is available for Checklist creation.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/fields/Due_Days__c.field-meta.xml
<CustomField>
    <fullName>Due_Days__c</fullName>
    <inlineHelpText>Number of days a checklist of this template is due from the date of creation.</inlineHelpText>
    <label>Due Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/fields/IsLocked__c.field-meta.xml
<CustomField>
    <fullName>IsLocked__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If the Template is locked, a checklist of this template can not be added with more items.</inlineHelpText>
    <label>Is Locked?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/fields/Sequential__c.field-meta.xml
<CustomField>
    <fullName>Sequential__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this is True, the items of the checklist need to be completed/checked sequentially from the top. Checking is not allowed if the previous item is not checked.</description>
    <label>Sequential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/fields/Template_Used_Count__c.field-meta.xml
<CustomField>
    <fullName>Template_Used_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Template Used Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Checklist_Template_Item__c/Checklist_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Checklist Template Item</label>
    <nameField>
        <displayFormat>CTI-{00}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Template_Item__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipLabel>Checklist Template Items</relationshipLabel>
    <relationshipName>Checklist_Template_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_Template_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist_Template_Item__c/fields/Item_Order__c.field-meta.xml
<CustomField>
    <fullName>Item_Order__c</fullName>
    <label>Item Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TemplateManager.cls
/*
     * @description: Controller class for LWC of Checklist Templates. To create and edit the Checklist Templates records
     * @Author: Kandisa Technologies
*/

public with sharing class TemplateManager {
    /*
     * @description: To fetch Checklist Template and it's Items when the View/Edit custom Lwc page of Checklist Templates object loads
     * @return: Checklist_Template__c
     * @param: recordId
    */    
    @AuraEnabled
    public static Checklist_Template__c getTemplateItems(String recordId){
        try {
            return [Select Id, Name, Due_Days__c, Active__c, IsLocked__c, Sequential__c, CreatedById, LastModifiedById, CreatedDate, LastModifiedDate, (Select Id, Item_Order__c, Item__c, Description__c From Checklist_Template_Items__r order by Item_Order__c ASC ) From Checklist_Template__c Where Id =: recordId WITH USER_MODE];
        } catch(QueryException  e){
            system.debug('test Exception '+e.getmessage());
            throw new AuraHandledException('Fetching Checklist Template Or Template Items Failed : '+e.getmessage());
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /*
     * @description: To save Checklist Template and Items and it's Items when the View/Edit custom Lwc page of Checklist Templates object loads
     * @return: Map<String, Object>
     * @param: Template, TemplateItems, DeletedTemplateItems
    */
    @AuraEnabled
    public static Map<String, Object> saveTemplateAndItems(String Template, List<Checklist_Template_Item__c> TemplateItems,
                                                        List<Checklist_Template_Item__c> DeletedTemplateItems,
                                                        Boolean updateRelatedOpenChecklist){

        Map<String, Object> response = new Map<String, Object>();
        try {
            
            system.debug('updateRelatedOpenChecklist : '+updateRelatedOpenChecklist);
            Checklist_Template__c TemplateRecord = (Checklist_Template__c) JSON.deserialize(Template, Checklist_Template__c.class);
            
            Map<Id, Checklist_Template_Item__c> oldMap;
            Checklist_Template__c oldTemp;
            if(TemplateRecord.Id != null){
                oldTemp = [Select id, Template_Used_Count__c from Checklist_Template__c where id =:TemplateRecord.Id WITH USER_MODE];
                oldMap = new Map<Id, Checklist_Template_Item__c>([Select Id, Item_Order__c, Item__c, Description__c From Checklist_Template_Item__c where Checklist_Template__c =:TemplateRecord.Id]);
            }
            
            
            List<Checklist_Template__c> lstTemplateRecord = new List<Checklist_Template__c>{TemplateRecord};
            if(lstTemplateRecord != null){
                system.debug('lstTemplateRecord- '+lstTemplateRecord);
                /*FLSChecker.FLSCheckWrapper fl = new FLSChecker.FLSCheckWrapper();
                fl = FLSChecker.dmlUpsert(lstTemplateRecord); 
                if(!fl.isSuccess){
                    throw new AuraHandledException(fl.message);
                }*/
                upsert as user lstTemplateRecord;
            }
        
            List<Checklist_Template_Item__c> updatedItems = new List<Checklist_Template_Item__c>();
            List<Checklist_Template_Item__c> updatedItemsforChecklists = new List<Checklist_Template_Item__c>();
            List<Checklist_Template_Item__c> insertedItems = new List<Checklist_Template_Item__c>();	
            
            if(!TemplateItems.isEmpty()){
                for(Checklist_Template_Item__c item : TemplateItems){

                    if(item.Checklist_Template__c == null){
                        item.Checklist_Template__c = TemplateRecord.Id;
                    }
                    
                    
                    if(item.Id == null){
                        updatedItems.add(item);
                    }else if(item.Id != null && oldMap != null && oldMap.containsKey(item.Id) && isItemUpdated(item, oldMap.get(item.Id)) ){
                        updatedItems.add(item);
                        /*if(updateRelatedOpenChecklist){
                            updatedItemsforChecklists.add(item);
                        } */
                    }else if(item.Id != null && oldMap != null && oldMap.containsKey(item.Id) && isItemOrderUpdated(item, oldMap.get(item.Id)) ){
                        updatedItems.add(item);
                    }
                    
                    
                }
                
                if(!updatedItems.isEmpty()){
                     /// update as user updatedItems; 
                        
                    Database.UpsertResult[] results = Database.upsert(updatedItems, AccessLevel.USER_MODE);
                    // if(updateRelatedOpenChecklist){
                        for(Integer index = 0, size = results.size(); index < size; index++) {
                            if(results[index].isCreated()){
                                insertedItems.add(updatedItems[index]);
                            }
                        }
                    // }
                }

            }
            
            if(!DeletedTemplateItems.isEmpty()){
                /*FLSChecker.FLSCheckWrapper fl3 = new FLSChecker.FLSCheckWrapper();
                fl3 = FLSChecker.dmlDelete(DeletedTemplateItems); 
                if(!fl3.isSuccess){
                    throw new AuraHandledException(fl3.message);
                }*/
                
                // database.executeBatch(new ChecklistItemsBatch(TemplateRecord, insertedItems, prepareMap(updatedItemsforChecklists), prepareMap(DeletedTemplateItems)), 1);
                delete as user DeletedTemplateItems;
            }
            
            // TemplateManagerWithoutSharing.createChecklistItems(TemplateRecord, insertedItems, new Map<Id, Checklist_Template_Item__c>(updatedItemsforChecklists), null);
            
            if(updateRelatedOpenChecklist){
                AggregateResult ag = [Select Count(Id) recordsCount From Checklist__c Where Checklist_Template__c = :TemplateRecord.Id AND Percentage_Completion__c < 100 WITH USER_MODE];
                Integer recordsCount = 0;
                if(ag.get('recordsCount') != null){
                    recordsCount = Integer.valueOf(ag.get('recordsCount'));
                }

                if(recordsCount > 5000){
                    database.executeBatch(new ChecklistItemsBatch(TemplateRecord, insertedItems), 2000);
                }else{
                    ChecklistItemsBatch.createChecklistItems([Select Id, Checklist_Item_Count__c, Checklist_Title__c, Percentage_Completion__c, Checklist_Template__c From Checklist__c Where Checklist_Template__c =:TemplateRecord.Id AND Percentage_Completion__c < 100 WITH USER_MODE ], insertedItems);
                }
            }
            
            response.put('recordId', TemplateRecord.Id);
            response.put('Status', 'Success');
            return response;
        } catch(AuraHandledException e){
            throw e;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    public static Boolean isItemUpdated(Checklist_Template_Item__c newItem, Checklist_Template_Item__c oldItem){        
        if(newItem.Item__c != oldItem.Item__c ||
            newItem.Description__c != oldItem.Description__c){
            return true;
        }else{
            return false;
        }
    }
    
    public static Boolean isItemOrderUpdated(Checklist_Template_Item__c newItem, Checklist_Template_Item__c oldItem){        
        if(newItem.Item_Order__c != oldItem.Item_Order__c){
            return true;
        }else{
            return false;
        }
    }
    
    /*
    private static Map<Id, checklist_Template_Item__c> prepareMap(List<Checklist_Template_Item__c> updatedItems){
        Map<Id, checklist_Template_Item__c> recMap = new Map<Id, checklist_Template_Item__c>();
        if(updatedItems != null){
            recMap = new Map<Id, checklist_Template_Item__c>(updatedItems);
        }
        return recMap;   
    }*/
}