force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>C-{00}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Predefined Checklist Items are auto-generated if a Checklist Template is selected.</inlineHelpText>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipLabel>Checklists</relationshipLabel>
    <relationshipName>Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Checklist_Title__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Title__c</fullName>
    <label>Checklist Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <formula>DATEVALUE(CreatedDate)+Due_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Due_Days__c.field-meta.xml
<CustomField>
    <fullName>Due_Days__c</fullName>
    <inlineHelpText>Number of days the checklist is due from the date of creation.</inlineHelpText>
    <label>Due Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Is_Checklist_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Checklist_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Checklist Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Is_Checklist_Template_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Checklist_Template_Locked__c</fullName>
    <formula>if(Checklist_Template__c != null, Checklist_Template__r.IsLocked__c, false )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Checklist Template Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Percentage_Completion__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Completion__c</fullName>
    <formula>FLOOR(( Checklist_Item_Checked_Count__c  /  Checklist_Item_Count__c ) * 100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percentage Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <label>Related To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <label>Related To Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Related_To_Object__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Object__c</fullName>
    <label>Related To Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Sequential__c.field-meta.xml
<CustomField>
    <fullName>Sequential__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sequential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Checklist Item</label>
    <nameField>
        <displayFormat>CI-{00}</displayFormat>
        <label>Checklist Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Item__c/fields/Checked__c.field-meta.xml
<CustomField>
    <fullName>Checked__c</fullName>
    <label>Checked</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <label>Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist Items</relationshipLabel>
    <relationshipName>Checklist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_Relationship__mdt/Checklist_Relationship__mdt.object-meta.xml
<CustomObject>
    <description>Create a record where adding a lookup field to a checklist is restricted.</description>
    <label>Checklist Relationship</label>
    <pluralLabel>Checklist Relationships</pluralLabel>
</CustomObject>

force-app/main/default/objects/Checklist_Relationship__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_Relationship__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>Sobject Api Name</description>
    <inlineHelpText>Sobject Api Name</inlineHelpText>
    <label>Object  Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Checklist Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Template__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/fields/Due_Days__c.field-meta.xml
<CustomField>
    <fullName>Due_Days__c</fullName>
    <inlineHelpText>Number of days a checklist of this template is due from the date of creation.</inlineHelpText>
    <label>Due Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/fields/Sequential__c.field-meta.xml
<CustomField>
    <fullName>Sequential__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this is True, the items of the checklist need to be completed/checked sequentially from the top. Checking is not allowed if the previous item is not checked.</description>
    <label>Sequential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ObjectKeyField__mdt/ObjectKeyField__mdt.object-meta.xml
<CustomObject>
    <description>To identify those sobjects where we are not considering the &quot;Name&quot; standard fields.</description>
    <label>ObjectKeyField</label>
    <pluralLabel>ObjectKeyFields</pluralLabel>
</CustomObject>

force-app/main/default/objects/ObjectKeyField__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <inlineHelpText>It is used to store Sobject field API name.</inlineHelpText>
    <label>Field Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MyChecklistsPageManagerDuc.cls
/*
     * @description: Controller class for LWC of Checklist Templates. To create and edit the Checklist Templates records
     * @Author: Kandisa Technologies
*/

public with sharing class MyChecklistsPageManagerDuc {
    /*
     * @description: To fetch Checklists and it's Items when the MyChecklist tab is opened or any category is clicked upon
     * @return: List<Checklist__c>
     * @param: userId
    */
    @AuraEnabled
    public Static List<Checklist__c> fetchCheckLists(String userId){
        System.debug('User Id:'+ userId);
        try{
           // Map<String, String> objectKeys = fetchObjectKeyFields();
            
            List<FieldNamesWrapper> fields = getFieldMap('kt_checklist__Checklist__c');
            //System.debug('**fields:'+fields);
            String query = 'Select Id, Name, Is_Checklist_Locked__c, Checklist_Title__c, Description__c, Percentage_Completion__c, Due_Days__c, Due_Date__c, CreatedById, CreatedDate, OwnerId, Is_Checklist_Template_Locked__c, Sequential__c,  '; //Template_Locked__c is removed.
            
            for(FieldNamesWrapper field: fields){
                if(!field.value.contains('Checklist_Template__c')){  // Remove "&& !field.value.contains('Assign_To_User__c')" condition after deleting fAssign_To_User__c field.
                    query += field.value + ', ';
                    if(field.value.endswith('__c')){
                        String keyField = '__r.Name';
                        //system.debug('field.relatedsobjectName'+field.relatedsobjectName);
                        ObjectKeyField__mdt objectKeyFields = ObjectKeyField__mdt.getInstance(field.relatedsobjectName);
                        if(objectKeyFields != null){
                            keyField = '__r.' + objectKeyFields.Field_Name__c;
                        }
                        //system.debug('keyField '+keyField);
                        query += field.value.replaceAll('__c', keyField) + ', ';
                    }
                }
            }
            
            Set<String> objects =  new Set<String>();
            for(Checklist_Relationship__mdt cr : [Select Id, Object_Name__c From Checklist_Relationship__mdt Where IsActive__c = true]){
                objects.add(cr.Object_Name__c);
            }
            
            objects.add('');
            
            // Adding other Related Fields
            query += 'Related_To_Id__c, Related_To_Object__c, Related_To__c, ';
                        
            query += '(Select Id, Item__c, Item_Order__c, Checked__c, Description__c, CreatedById From CheckList_Items__r order by Item_Order__c ASC) '
                + 'From Checklist__c WHERE OwnerId = :ownerId AND Related_To_Object__c IN: objects Order By Due_Date__c Asc';
            
            // System.debug('**Query:'+query);
            
            List<Checklist__c> checklistRecords = Database.queryWithBinds(query, new Map<String, Object>{'ownerId' => userId, 'objects' => objects}, Accesslevel.USER_MODE);
            
            // System.debug('**checklistRecords:'+checklistRecords);
            
            return checklistRecords;
        } catch(QueryException  e){
            // system.debug('test Exception '+e.getmessage());
            String errorMessage = e.getmessage();
            if(errorMessage.startsWithIgnoreCase('No such column \'Name\' on entity')){
                    // Extract the column name and entity from the error message
                    // This assumes the error message follows the format: "No such column 'ColumnName' on entity 'EntityName'."
                    Pattern regex = Pattern.compile('No such column \'(.*?)\' on entity \'(.*?)\'.');
                    Matcher matcher = regex.matcher(errorMessage);
                    
                    if(matcher.find()) {
                        String columnName = matcher.group(1);
                        String entityName = matcher.group(2);
                        
                        errorMessage = 'No such Field \'' + columnName + '\' on entity \'' + entityName + '\'. Please ensure that the field exists or create a corresponding record in the ObjectKeyField custom metadata.';
                    }
            }
            throw new AuraHandledException('Fetching Checklist Or Items Failed : '+errorMessage);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /*
     * @description: To get field map of the object kt_checklist__Checklist__c
     * @return: List<FieldNamesWrapper>
     * @param: sObjectType
    */
    public static List<FieldNamesWrapper> getFieldMap(String sObjectType) {
        List<FieldNamesWrapper> options = new List<FieldNamesWrapper>();
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType targetType = schemaMap.get(sObjectType);
        Map<String, Schema.SObjectField> fieldMap = targetType.getDescribe().fields.getMap();
        // System.debug('**fieldMap:'+fieldMap);
        for(String fieldName : fieldMap.keySet()){
            Schema.DescribeFieldResult fieldDescribe = fieldMap.get(fieldName).getDescribe();
            String apiName = fieldDescribe.getName();
            // System.debug('**apiName:'+apiName);
            if(String.isNotBlank(apiName) && fieldDescribe.getType() == Schema.DisplayType.REFERENCE && fieldDescribe.isCustom()){
                System.debug('**apiName2:'+apiName);
                options.add(new FieldNamesWrapper(fieldMap.get(fieldName).getDescribe().getLabel(), apiName, String.ValueOF(fieldMap.get(fieldName).getDescribe().getType()), String.valueOf(fieldDescribe.getReferenceTo()[0]) ));
            }
        }
        return options;
    }
    
    /*
     * @description: To get the related object name and pass it to getIconName method and get the icon name and return a map with object name vs its icon name
     * @return: Map<String, String>
     * @param: objectApiName
    */
    
    /*
     * Migrated the logic to fetchIcons
     * 
    @AuraEnabled (cacheable = true)
    public static Map<String, String> getRelationObjectIconFieldMap(String objectApiName){
        Map<String, String> relationshipFields = new Map<String, String>();
        Schema.DescribeSObjectResult testObjectDescribe = Schema.getGlobalDescribe().get(objectApiName).getDescribe();
        List<Schema.SObjectField> fields = testObjectDescribe.fields.getMap().values();
        for (Schema.SObjectField field : fields) {
            if (field.getDescribe().getType() == Schema.DisplayType.REFERENCE && !field.getDescribe().isNamePointing() ) {
                String relatedObjectName = field.getDescribe().getReferenceTo()[0].getDescribe().getName();
                
                String icon = getIconName(relatedObjectName);
                relationshipFields.put(field.getDescribe().getName(), icon);
            }
        }
        return relationshipFields;
    }
    */
    
    private static Map<String, String> getRelationObjectFieldMap(String objectApiName){
        Map<String, String> relationshipFields = new Map<String, String>();
        Schema.DescribeSObjectResult testObjectDescribe = Schema.getGlobalDescribe().get(objectApiName).getDescribe();
        List<Schema.SObjectField> fields = testObjectDescribe.fields.getMap().values();
        for (Schema.SObjectField field : fields) {
            if (field.getDescribe().isCustom() && field.getDescribe().getType() == Schema.DisplayType.REFERENCE && !field.getDescribe().isNamePointing() ) {
                String relatedObjectName = field.getDescribe().getReferenceTo()[0].getDescribe().getName();
                
                relationshipFields.put(field.getDescribe().getName(), relatedObjectName);
            }
        }
        return relationshipFields;
    }
    
    @AuraEnabled (cacheable = true)
    public static Map<String, String> fetchIcons(List<String> sObjectTypes, String objectApiName){
        Map<String, String> relationshipFields = getRelationObjectFieldMap(objectApiName);
        /*
        List<String> objectNames = new List<String>();
        objectNames = relationshipFields.values();
        String checklistObejctId = '01IHu000003GFE6';
        
        for(FieldDefinition field : [SELECT DurableId, DataType, DeveloperName, ReferenceTo, IsSearchPrefilterable  from FieldDefinition where  EntityDefinitionId =:checklistObejctId and  IsSearchPrefilterable  = true]){
            system.debug('field.ReferenceTo'+field.ReferenceTo);
        }
		*/
        for(String obj : sObjectTypes){
            relationshipFields.put(obj, obj);
        }
        
        Map<String, String> relationshipIcons = new Map<String, String>();
        Map<String, String> objIconMap = new Map<String, String>();
        for(TabDefinition tab : [SELECT DurableId, IsCustom, SobjectName, (Select Id, url from Icons where ContentType = 'image/svg+xml') from TabDefinition where SobjectName IN :relationshipFields.values() WITH SYSTEM_MODE]){
            String url = !tab.Icons.isEmpty() ? tab.Icons[0].url : ''; 
            
            if(tab.IsCustom){
                url = 'custom:' + url.substringBetween('custom/','.svg');
            }else{
                url = 'standard:' + url.substringBetween('standard/','.svg');
            }
            objIconMap.put(tab.SobjectName, url);
        }
        
        for(String field :  relationshipFields.keySet()){
            String objName = relationshipFields.get(field);
            String iconUrl = objIconMap.containsKey(objName) ? objIconMap.get(objName) : '';
            if(String.isNotBlank(iconUrl)){
                relationshipIcons.put(field, iconUrl);
            }
        }
        return relationshipIcons;
    }
    
    /*
     * @description: To get the icon name of the supplied standard or custom object name
     * @return: String
     * @param: sobjectApiName
    */
    /*
    @AuraEnabled
    public static String getIconName(String sobjectApiName){
        String iconName;
        List<Schema.DescribeTabSetResult> tabSetDesc = Schema.DescribeTabs();
        List<Schema.DescribeTabResult> tabDesc = new List<Schema.DescribeTabResult>();
        List<Schema.DescribeIconResult> iconDesc = new List<Schema.DescribeIconResult>();
        
        for(Schema.DescribeTabSetResult tsr : tabSetDesc) { 
            tabDesc.addAll(tsr.getTabs()); 
        }
        
        for(Schema.DescribeTabResult tr : tabDesc) {
            if( sobjectApiName == tr.getSobjectName() ) {
                if( tr.isCustom() ) {
                    iconDesc.addAll(tr.getIcons());
                } else {
                    iconName = 'standard:' + sobjectApiName.toLowerCase();
                }
            }
        }
        for (Schema.DescribeIconResult ir : iconDesc) {
            if (ir.getContentType() == 'image/svg+xml'){
                iconName = 'custom:' + ir.getUrl().substringBetween('custom/','.svg').substringBefore('_');
                break;
            }
        }
        return iconName;
    }
*/
  // Updated to below 
    /*Migrated the logic to fetchIcons
    @AuraEnabled 
    public static String getIconName(String sobjectApiName){
        String iconName;
        Boolean isCustomObject = false;
        List<Schema.DescribeTabSetResult> tabSetDesc = Schema.DescribeTabs();
        List<Schema.DescribeTabResult> tabDesc = new List<Schema.DescribeTabResult>();
        List<Schema.DescribeIconResult> iconDesc = new List<Schema.DescribeIconResult>();
        
        for(Schema.DescribeTabSetResult tsr : tabSetDesc) { 
            tabDesc.addAll(tsr.getTabs()); 
        }
        
        for(Schema.DescribeTabResult tr : tabDesc) {
            if( sobjectApiName == tr.getSobjectName() ) {
                isCustomObject = tr.isCustom();
                iconDesc.addAll(tr.getIcons());
            }
        }
        for (Schema.DescribeIconResult ir : iconDesc) {
            system.debug('ir..getUrl()'+ir.getUrl());
            system.debug('ir.getContentType()'+ir.getContentType());
            if (ir.getContentType() == 'image/svg+xml'){
                system.debug('ir.getUrl()'+ir.getUrl());
                if(isCustomObject){
                    iconName = 'custom:' + ir.getUrl().substringBetween('custom/','.svg').substringBefore('_');
                    break;
                }else{
                    iconName = 'standard:' + ir.getUrl().substringBetween('standard/','.svg');
                    break;
                }
                
            }
        }
        return iconName;
    }
    */
    
    public class FieldNamesWrapper {
        /**
        * @description This variable will hold field label
        */
        @AuraEnabled public String label { get; set; }
        /**
        * @description This variable will hold field value
        */
        @AuraEnabled public String value { get; set; }
        /**
        * @description This variable will hold field Type
        */
        @AuraEnabled public String fieldType { get; set; }
        
        /**
        * @description This variable will hold field Type
        */
        @AuraEnabled public String relatedsobjectName { get; set; }
        
        /**
        * @description Constructor of FieldNamesWrapper
        * @param label
        * @param value
        * @param fieldType
        */
        public FieldNamesWrapper(String label, String value, String fieldType, String relatedsobjectName) {
            this.label = label;
            this.value = value;
            this.fieldType = fieldType;
            this.relatedsobjectName = relatedsobjectName;
        }
    }
    
    /**
     *  @description Return object key fields.
     *
     * @return Map of object key fields.
     
    public static Map<String, String> fetchObjectKeyFields() {
        Map<String, String> objectKeyFieldMap = new Map<String, String>();

        for (ObjectKeyField__mdt objectKeyFieldMdt : [
            SELECT Id, MasterLabel, Field_Name__c
            FROM ObjectKeyField__mdt 
        ]) {
            objectKeyFieldMap.put(objectKeyFieldMdt.MasterLabel, objectKeyFieldMdt.Field_Name__c);
        }
        return objectKeyFieldMap;
    }
	*/
    
}