force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>C-{00}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/Checklist_Item_Count__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Item_Count__c</fullName>
    <label>Checklist Item Count</label>
    <summaryForeignKey>Checklist_Item__c.Checklist__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Predefined Checklist Items are auto-generated if a Checklist Template is selected.</inlineHelpText>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipLabel>Checklists</relationshipLabel>
    <relationshipName>Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Checklist_Title__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Title__c</fullName>
    <label>Checklist Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Percentage_Completion__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Completion__c</fullName>
    <formula>FLOOR(( Checklist_Item_Checked_Count__c  /  Checklist_Item_Count__c ) * 100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percentage Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Checklist Item</label>
    <nameField>
        <displayFormat>CI-{00}</displayFormat>
        <label>Checklist Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Item__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <label>Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist Items</relationshipLabel>
    <relationshipName>Checklist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_Item__c/fields/Checklist_Template_Item__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Template Item</label>
    <referenceTo>Checklist_Template_Item__c</referenceTo>
    <relationshipLabel>Checklist Items</relationshipLabel>
    <relationshipName>Checklist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Template__c/Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Checklist Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Template__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Checklist_Template_Item__c/Checklist_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Checklist Template Item</label>
    <nameField>
        <displayFormat>CTI-{00}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Template_Item__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipLabel>Checklist Template Items</relationshipLabel>
    <relationshipName>Checklist_Template_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_Template_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist_Template_Item__c/fields/Item_Order__c.field-meta.xml
<CustomField>
    <fullName>Item_Order__c</fullName>
    <label>Item Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ChecklistItemsBatch.cls
public without sharing class ChecklistItemsBatch implements Database.Batchable<sObject>{
    public Checklist_Template__c template;
    public List<Checklist_Template_Item__c> insertedList;
    public ChecklistItemsBatch(Checklist_Template__c temp, List<Checklist_Template_Item__c> newList){
        template = temp;
        insertedList = newList;
        // updatedMap = updateMap;
        // deleteMap = deleteTempMap;        
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String templateId = template.id;
        return Database.getQueryLocator('Select Id, Checklist_Item_Count__c, Checklist_Title__c, Percentage_Completion__c, Checklist_Template__c From Checklist__c Where Checklist_Template__c =:templateId AND Percentage_Completion__c < 100 WITH SYSTEM_MODE');
    }

    public void execute(Database.BatchableContext bc, List<CheckList__c> checklists) {
        system.debug('Batch execute');
        
        createChecklistItems(checklists, insertedList);
    }

    public static void createChecklistItems(List<CheckList__c> checklists, List<Checklist_Template_Item__c> insertedList){
        List<Checklist_Item__c> items = new List<Checklist_Item__c>();
        for(CheckList__c checklist : checklists){
            items.addAll(fetchItemsToInsert(checklist, insertedList));
        }

        if(!items.isEmpty()){
            insert as system items;
        }  
    }

    private static List<CheckList_Item__c> fetchItemsToInsert(CheckList__c checklist, List<Checklist_Template_Item__c> tempItems){
        List<Checklist_Item__c> items = new List<Checklist_Item__c>();
        
        Integer itemsCount = (Integer) checklist.Checklist_Item_Count__c;
        for(Checklist_Template_Item__c tempItem : tempItems){
            Checklist_Item__c item = new Checklist_Item__c();
            item.Item__c = tempItem.Item__c;
            item.Item_Order__c = ++itemsCount;
            item.Description__c = tempItem.Description__c;
            item.Checklist__c = checklist.Id;
            
            item.Checklist_Template_Item__c = tempItem.Id;
            items.add(item);
        }
        return items;
    }
    
    public void finish(Database.BatchableContext bc) {
        
    }
    
    /*

    public Checklist_Template__c template;
    public List<Checklist_Template_Item__c> insertedList;
    public Map<Id, Checklist_Template_Item__c> updatedMap; 
    public Map<Id, Checklist_Template_Item__c> deleteMap;
    
    
    public ChecklistItemsBatch(Checklist_Template__c temp, List<Checklist_Template_Item__c> newList,
                            Map<Id, Checklist_Template_Item__c> updateMap, 
                            Map<Id, Checklist_Template_Item__c> deleteTempMap)
    {
        system.debug('Batch constructor');
        template = temp;
        insertedList = newList;
        updatedMap = updateMap;
        deleteMap = deleteTempMap;        
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        system.debug('Batch start');
        system.debug('template : '+template);
        String templateId = template.id;
        system.debug('templateId : '+templateId);
        return Database.getQueryLocator('Select Id, Checklist_Item_Count__c, Checklist_Title__c, Percentage_Completion__c, Checklist_Template__c, (Select Id, Item__c, Item_Order__c, Description__c, Checklist__c, Checklist_Template_Item__c From CheckList_Items__r Where Checklist_Template_Item__c != null) From Checklist__c Where Checklist_Template__c =:templateId WITH SYSTEM_MODE');
    }

    public void execute(Database.BatchableContext bc, List<CheckList__c> checklists) {
        system.debug('Batch execute');
        createChecklistItems(checklists, insertedList, updatedMap, deleteMap);
    }
    
    public static void createChecklistItems(List<CheckList__c> checklists, List<Checklist_Template_Item__c> insertedList, Map<Id, Checklist_Template_Item__c> updatedMap, Map<Id, Checklist_Template_Item__c> deleteMap){
                
        List<CheckList_Item__c> upsertList = new List<CheckList_Item__c>();
        List<CheckList_Item__c> deleteList = new List<CheckList_Item__c>();
        
        system.debug('st : '+deleteMap);
        for(CheckList__c checklist : checklists){
                        
            List<CheckList_Item__c> items = fetchItemsToInsert(insertedList, checklist);
            if(!items.isEmpty()){
                upsertList.addAll(items);
            }
            
            for(CheckList_Item__c item : checklist.CheckList_Items__r){
                system.debug('item : '+item.Checklist_Template_Item__c);
                system.debug('item : '+deleteMap.keySet().contains(item.Checklist_Template_Item__c));
                if(deleteMap.keySet().contains(item.Checklist_Template_Item__c)){
                    system.debug('item : '+item);
                    deleteList.add(item);
                    continue;
                }
                
                if(updatedMap.containsKey(item.Checklist_Template_Item__c)){
                    upsertList.add(updateChecklistItemFields(updatedMap.get(item.Checklist_Template_Item__c), item));
                }
            }
        }

        if(!upsertList.isEmpty()){
            upsert as system upsertList;
        }
        
        if(!deleteList.isEmpty()){
            delete as system deleteList;
        } 
        
    }
    
    private static CheckList_Item__c updateChecklistItemFields(Checklist_Template_Item__c tempItem, CheckList_Item__c item){
        item.Item__c = tempItem.Item__c;
        item.Description__c = tempItem.Description__c;
        return item;
    }
    
    private static List<CheckList_Item__c> fetchItemsToInsert(List<Checklist_Template_Item__c> tempItems, CheckList__c checklist){
        List<Checklist_Item__c> items = new List<Checklist_Item__c>();
        
        Integer itemsCount = (Integer) checklist.Checklist_Item_Count__c;
        for(Checklist_Template_Item__c tempItem : tempItems){
            Checklist_Item__c item = new Checklist_Item__c();
            item.Item__c = tempItem.Item__c;
            item.Item_Order__c = ++itemsCount;
            item.Description__c = tempItem.Description__c;
            item.Checklist__c = checklist.Id;
            
            item.Checklist_Template_Item__c = tempItem.Id;
            items.add(item);
        }
        return items;
    }

    public void finish(Database.BatchableContext bc) {
        if(!deleteMap.isEmpty()) delete deleteMap.values();
        
    }
	*/
    
    
}